<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_g7sycJiTEeuiH60Puc3mNA" name="AchizitieImobilDiagram" author="unciu" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_g7sycZiTEeuiH60Puc3mNA" name="Achizitie Imobil">
      <elements xmi:type="process:Lane" xmi:id="_g7sycpiTEeuiH60Puc3mNA" name="Cumpărător" actor="_zX-ggJiTEeuiH60Puc3mNA">
        <elements xmi:type="process:StartEvent" xmi:id="_g7syc5iTEeuiH60Puc3mNA" name="Accesare platformă" outgoing="_g7syiJiTEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g7sydJiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g7sydZiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g7sydpiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_g7syd5iTEeuiH60Puc3mNA" name="Selectează filtre" outgoing="_2iM5cJiWEeuiH60Puc3mNA" incoming="_g7syiJiTEeuiH60Puc3mNA" actor="_zX-ggJiTEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_g7syeJiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_g7syeZiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_g7syepiTEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_g7sye5iTEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_g7syfJiTEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_g7syfZiTEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_g7syfpiTEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_g7syf5iTEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_g7sygJiTEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_h2Gi4Jx9Eeumk8Ucz-RH9A" name="filtreCautare" content="fcd352b7-df6d-4eb1-a4ac-31ccf4267902" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_g7sygpiTEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_g7syg5iTEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_6DeAwJiWEeuiH60Puc3mNA" name="Vizualizează listă imobile" outgoing="_7fi9MJiWEeuiH60Puc3mNA" incoming="_2iM5cJiWEeuiH60Puc3mNA _8PIVIJiYEeuiH60Puc3mNA _elyU4JicEeuMnLTQnxFs6A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2iIA8piWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2iIA8ZiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2iIA85iWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2iIA9JiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2iIA9ZiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2iIA9piWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2iIA-JiWEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2iIA95iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6DfO6JiWEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_h2Gi4Zx9Eeumk8Ucz-RH9A" name="listaImobileCumparator" content="a2dd8dbd-6125-4d68-aecf-18bb5a186864" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6DfO55iWEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6DfO6piWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-vyl8JiWEeuiH60Puc3mNA" name="Contactează agent" outgoing="_I7yf4JiXEeuiH60Puc3mNA" incoming="_7fi9MJiWEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7feEsZiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7feEsJiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7feEspiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7feEs5iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7feEtJiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7feEtZiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7feEt5iWEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7feEtpiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-vyl-piWEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_h2Gi4px9Eeumk8Ucz-RH9A" name="contactAgent" content="16d1e70b-6b64-45d4-bbdf-27950bbeeeff" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-vyl-ZiWEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-vyl_JiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_HMcpMJiXEeuiH60Puc3mNA" name="Încadrare tip utilizator" outgoing="_bIXlEJiXEeuiH60Puc3mNA _ZEkE0JiYEeuiH60Puc3mNA" incoming="_I7yf4JiXEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HMdQQZiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HMdQQJiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HMdQQpiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_tbPfgJiXEeuiH60Puc3mNA" name="Redirecționează spre pagina de login" outgoing="_vIBKYJiXEeuiH60Puc3mNA" incoming="_bIXlEJiXEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bITToZiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bITToJiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bITTopiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_bITTo5iXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_bITTpJiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bITTpZiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_bITTp5iXEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_bITTppiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_23xrYJiXEeuiH60Puc3mNA" name="Existență cont" outgoing="_3tjc0JiXEeuiH60Puc3mNA _KM9XYJiYEeuiH60Puc3mNA" incoming="_vIBKYJiXEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vH9gAZiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vH9gAJiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vH9gApiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_E5zbsJiYEeuiH60Puc3mNA" name="Redirecționează către pagina de înregistrare" outgoing="_D6qS4JiYEeuiH60Puc3mNA" incoming="_3tjc0JiXEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3tfLYpiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3tfLYZiXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3tfLY5iXEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3tfycJiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3tfycZiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3tfycpiXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3tfydJiXEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3tfyc5iXEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_JIFaAJiYEeuiH60Puc3mNA" name="Creează cont" outgoing="_mwHO0JiYEeuiH60Puc3mNA" incoming="_D6qS4JiYEeuiH60Puc3mNA" actor="_zX-ggJiTEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D6kMQpiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D6kMQZiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D6kMQ5iYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D6kMRJiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D6kMRZiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D6kMRpiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D6kMSJiYEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D6kMR5iYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JIFaCpiYEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_h2Gi45x9Eeumk8Ucz-RH9A" name="creeazaCont" content="624585d2-cd70-48e1-9580-48694218c192" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JIFaCZiYEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_JIFaDJiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_P00XwJiYEeuiH60Puc3mNA" name="Efectuează login" outgoing="_F3FG0JiZEeuiH60Puc3mNA" incoming="_KM9XYJiYEeuiH60Puc3mNA _ZEkE0JiYEeuiH60Puc3mNA _BocjMJiZEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KM2psZiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KM2psJiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KM2pspiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KM2ps5iYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KM2ptJiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KM2ptZiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KM2pt5iYEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KM2ptpiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_P00-1piYEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_1SU0MKOSEeuF1NgcLbyZ9A" name="autentificareCumparator" content="7ab3d5f6-c478-49bc-bd7f-6edb4e639edd" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_P00-1ZiYEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_P00-2JiYEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_NfrP4JiZEeuiH60Puc3mNA" name="Creare cont" outgoing="_8PIVIJiYEeuiH60Puc3mNA _BocjMJiZEeuiH60Puc3mNA" incoming="_mwHO0JiYEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lTvXcZiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lTvXcJiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lTvXcpiYEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_BxpGAJiaEeuiH60Puc3mNA" name="Înregistrează formular" outgoing="_PUJBsJiaEeuiH60Puc3mNA" incoming="_Bxt-gJiaEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BxptEJiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BxpGAZiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BxptEZiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BxptEpiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BxptE5iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BxptFJiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BxptFpiaEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BxptFZiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_DQqBsJiaEeuiH60Puc3mNA" name="Completează formular" outgoing="_Bxt-gJiaEeuiH60Puc3mNA" incoming="_F3FG0JiZEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F3AOUpiZEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F3AOUZiZEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F3AOU5iZEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F3AOVJiZEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F3AOVZiZEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F3AOVpiZEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F3AOWJiZEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F3AOV5iZEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_DQqoyZiaEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_cHtl4aOSEeuF1NgcLbyZ9A" name="contactAgent" content="16d1e70b-6b64-45d4-bbdf-27950bbeeeff" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_DQqoyJiaEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_DQqoy5iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_LM5qEJibEeuiH60Puc3mNA" name="3 zile" outgoing="_BcAiUJicEeuMnLTQnxFs6A" incoming="_j0UrwJibEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LM6RIJibEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LM5qEZibEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LM6RIZibEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_c1WugJibEeuiH60Puc3mNA" name="3 Days 00:00:00" content="259200000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_Bw7CYJicEeuMnLTQnxFs6A" name="Decizie achiziție" outgoing="_EMOnMJicEeuMnLTQnxFs6A _FQqfsJicEeuMnLTQnxFs6A" incoming="_BcAiUJicEeuMnLTQnxFs6A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BbryMJicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BbrLIJicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BbryMZicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_X2mgEJicEeuMnLTQnxFs6A" name="Anulează achiziție" outgoing="_YZpiwJicEeuMnLTQnxFs6A" incoming="_EMOnMJicEeuMnLTQnxFs6A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EME2MZicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EME2MJicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EME2MpicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EME2M5icEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EMFdQJicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EMFdQZicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EMFdQ5icEeuMnLTQnxFs6A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EMFdQpicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_YraoMJicEeuMnLTQnxFs6A" name="Redirecționează spre listă anunțuri" outgoing="_elyU4JicEeuMnLTQnxFs6A" incoming="_YZpiwJicEeuMnLTQnxFs6A _5NVWwJx3EeunR90isTkFuQ _DzUBgJx5Eeumk8Ucz-RH9A _rRp0IJx5Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YZkDMZicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YZkDMJicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YZkDMpicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YZkDM5icEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YZkDNJicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YZkDNZicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YZkDN5icEeuMnLTQnxFs6A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YZkDNpicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_1Wnj4Jx3EeunR90isTkFuQ" name="Decizie semnare antecontract" outgoing="_5NVWwJx3EeunR90isTkFuQ _-UNxAJx3EeunR90isTkFuQ" incoming="_0vD0oJx3EeunR90isTkFuQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0u41gZx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0u41gJx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0u41gpx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-01KwJx3EeunR90isTkFuQ" name="Semnează antecontract și înregistrează dovezi de plată" outgoing="_0vD0oJx3EeunR90isTkFuQ" incoming="_ZvISgJidEeuMnLTQnxFs6A _cnuLwJx4Eeumk8Ucz-RH9A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZvCy8ZidEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZvCy8JidEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZvCy8pidEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZvCy85idEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZvCy9JidEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZvCy9ZidEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZvCy95idEeuMnLTQnxFs6A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZvCy9pidEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-01x2Zx3EeunR90isTkFuQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_QTnBU6N0Eeud8f3be_xEeA" name="semnareAntecontract" content="a69b728a-4b49-4d40-adbe-37b318213a4a" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-01x2Jx3EeunR90isTkFuQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-01x25x3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zLt9IJx4Eeumk8Ucz-RH9A" name="Semnează contract și înregistrează dovada plății imobilului" outgoing="_7aIwEJx4Eeumk8Ucz-RH9A" incoming="_wX_RQJx4Eeumk8Ucz-RH9A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wX5xsZx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wX5xsJx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wX5xspx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wX5xs5x4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wX5xtJx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wX5xtZx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wX5xt5x4Eeumk8Ucz-RH9A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wX5xtpx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zLukOZx4Eeumk8Ucz-RH9A">
            <targetForm xmi:type="expression:Expression" xmi:id="_7RkWo6OOEeuF1NgcLbyZ9A" name="semnareContract" content="324409d8-c1bf-4c4b-a127-9a653700175b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zLukOJx4Eeumk8Ucz-RH9A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zLukO5x4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_DN188Jx5Eeumk8Ucz-RH9A" name="Decizie semnare contract" outgoing="_DzUBgJx5Eeumk8Ucz-RH9A _KEr48Jx5Eeumk8Ucz-RH9A" incoming="_7aIwEJx4Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7aFFspx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7aFFsZx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7aFFs5x4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_DUMfwJx9Eeumk8Ucz-RH9A" name="Confirmă achiziția" outgoing="_DpI1AJx9Eeumk8Ucz-RH9A" incoming="_DUTNcJx9Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DUOU8Jx9Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DUNt4Jx9Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DUOU8Zx9Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DUOU8px9Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DUOU85x9Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DUOU9Jx9Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DUOU9px9Eeumk8Ucz-RH9A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DUOU9Zx9Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_vpjRgJiUEeuiH60Puc3mNA" name="Agent imobiliar" actor="_5zfycJiTEeuiH60Puc3mNA">
        <elements xmi:type="process:StartEvent" xmi:id="_Lv4DAJiVEeuiH60Puc3mNA" name="Vizionare agendă de lucru" outgoing="_PXqpEJiVEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Lv4qEZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Lv4qEJiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Lv4qEpiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ScPNUJiVEeuiH60Puc3mNA" name="Autentifică agent imobiliar" outgoing="_rUgHYJiVEeuiH60Puc3mNA" incoming="_PXqpEJiVEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PXfp8piVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PXfp8ZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PXfp85iVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PXfp9JiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PXfp9ZiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PXfp9piVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PXgRAJiVEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PXfp95iVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ScRChJiVEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_QTnBVaN0Eeud8f3be_xEeA" name="autentificareAgent" content="bab1f106-eadd-49b2-a320-30c96c9eb93d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ScRCg5iVEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ScRChpiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_h62QYJiVEeuiH60Puc3mNA" name="Credențiale introduse" outgoing="_uAksEJiVEeuiH60Puc3mNA" incoming="_rUgHYJiVEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h62QYpiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h62QYZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h62QY5iVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ScriptTask" xmi:id="_wlijMJiVEeuiH60Puc3mNA" name="Autentifică utilizator" outgoing="_8Sjj8JiVEeuiH60Puc3mNA" incoming="_uAksEJiVEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uAdXUJiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uAcwQZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uAdXUZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uAdXUpiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uAdXU5iVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uAdXVJiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uAdXVpiVEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uAdXVZiVEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_8Sc2QJiVEeuiH60Puc3mNA" name="Activitate selectată" outgoing="_WGmw0JiWEeuiH60Puc3mNA _YEEjEJiWEeuiH60Puc3mNA" incoming="_8Sjj8JiVEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8SddUZiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8SddUJiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8SddUpiVEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_nKKYcJiWEeuiH60Puc3mNA" name="Administrează anunțuri" incoming="_YEEjEJiWEeuiH60Puc3mNA" actor="_5zfycJiTEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YD-ccZiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YD-ccJiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YD-ccpiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YD-cc5iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YD-cdJiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YD-cdZiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YD-cd5iWEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YD-cdpiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_nKK_iZiWEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoALD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_nKK_iJiWEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_nKK_i5iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zeHdYJiWEeuiH60Puc3mNA" name="Administrează cereri de contact" outgoing="_NomF4JiaEeuiH60Puc3mNA" incoming="_WGmw0JiWEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WGh4UpiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WGh4UZiWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WGh4U5iWEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WGh4VJiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WGh4VZiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WGh4VpiWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WGh4WJiWEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WGh4V5iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zeIEeZiWEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoAbD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zeIEeJiWEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zeIEe5iWEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_NohNYJiaEeuiH60Puc3mNA" name="Actualizare status solicitări" outgoing="_oo5DcJiaEeuiH60Puc3mNA" incoming="_NomF4JiaEeuiH60Puc3mNA _PUJBsJiaEeuiH60Puc3mNA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Noh0cZiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Noh0cJiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Noh0cpiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_shCZsJiaEeuiH60Puc3mNA" name="Stabilește vizită imobil" outgoing="_zD6Q0JiaEeuiH60Puc3mNA" incoming="_oo5DcJiaEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oo0yAZiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oo0yAJiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oo0yApiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oo0yA5iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oo0yBJiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oo0yBZiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oo0yB5iaEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oo0yBpiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_shDn1ZiaEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoArD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_shDn1JiaEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_shDn15iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__ZmEsJx3EeunR90isTkFuQ" name="Pregătește antecontract" outgoing="_ZvISgJidEeuMnLTQnxFs6A" incoming="_FQqfsJicEeuMnLTQnxFs6A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FQhVwZicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FQhVwJicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FQhVwpicEeuMnLTQnxFs6A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FQhVw5icEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FQhVxJicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FQhVxZicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FQhVx5icEeuMnLTQnxFs6A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FQhVxpicEeuMnLTQnxFs6A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__ZmEupx3EeunR90isTkFuQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoA7D0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__ZmEuZx3EeunR90isTkFuQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__ZmEvJx3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SbwuEJx4Eeumk8Ucz-RH9A" name="Validează dovezi de plată" outgoing="_V-GzcJx4Eeumk8Ucz-RH9A" incoming="_-UNxAJx3EeunR90isTkFuQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-UI4gZx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-UI4gJx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-UI4gpx3EeunR90isTkFuQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-UI4g5x3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-UI4hJx3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-UI4hZx3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-UI4h5x3EeunR90isTkFuQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-UI4hpx3EeunR90isTkFuQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Sb20spx4Eeumk8Ucz-RH9A">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoBLD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Sb20sZx4Eeumk8Ucz-RH9A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Sb20tJx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_WV5BUJx4Eeumk8Ucz-RH9A" name="Documente verificate" outgoing="_cnuLwJx4Eeumk8Ucz-RH9A _f_pJ0Jx4Eeumk8Ucz-RH9A" incoming="_V-GzcJx4Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_V9-3oZx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_V9-3oJx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_V9-3opx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_h3HBwJx4Eeumk8Ucz-RH9A" name="Pregătire contract" outgoing="_wX_RQJx4Eeumk8Ucz-RH9A" incoming="_f_pJ0Jx4Eeumk8Ucz-RH9A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f_kRUpx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f_kRUZx4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f_kRU5x4Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f_kRVJx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f_kRVZx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f_kRVpx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f_kRWJx4Eeumk8Ucz-RH9A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f_kRV5x4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_h3KFGJx4Eeumk8Ucz-RH9A">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoBbD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_h3KFF5x4Eeumk8Ucz-RH9A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_h3KFGpx4Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_N7EUoJx5Eeumk8Ucz-RH9A" name="Validează plată imobil" outgoing="_dsipUJx5Eeumk8Ucz-RH9A" incoming="_KEr48Jx5Eeumk8Ucz-RH9A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KEmZYpx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KEmZYZx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KEmZY5x5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KEmZZJx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KEmZZZx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KEmZZpx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KEmZaJx5Eeumk8Ucz-RH9A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KEmZZ5x5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_N7E7tpx5Eeumk8Ucz-RH9A">
            <targetForm xmi:type="expression:Expression" xmi:id="_r4JoBrD0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_N7E7tZx5Eeumk8Ucz-RH9A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_N7E7uJx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_gdBM4Jx5Eeumk8Ucz-RH9A" name="Status plată" outgoing="_hqGEAJx5Eeumk8Ucz-RH9A _rRp0IJx5Eeumk8Ucz-RH9A _DUTNcJx9Eeumk8Ucz-RH9A" incoming="_dsipUJx5Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dseX4Zx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dseX4Jx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dseX4px5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_hqAkcJx5Eeumk8Ucz-RH9A" name="Achiziționează imobil" outgoing="_xXns0Jx5Eeumk8Ucz-RH9A" incoming="_hqGEAJx5Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hqBykZx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hqBykJx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hqBykpx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_hqByk5x5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_hqBylJx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_hqBylZx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_hqByl5x5Eeumk8Ucz-RH9A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_hqBylpx5Eeumk8Ucz-RH9A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_usoGMJx5Eeumk8Ucz-RH9A" name="Imobil achiziționat" incoming="_xXns0Jx5Eeumk8Ucz-RH9A _DpI1AJx9Eeumk8Ucz-RH9A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_usp7YZx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_usp7YJx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_usp7Ypx5Eeumk8Ucz-RH9A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0yDNoJiaEeuiH60Puc3mNA" name="Vizitează imobil" outgoing="_j0UrwJibEeuiH60Puc3mNA" incoming="_zD6Q0JiaEeuiH60Puc3mNA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zD0xQpiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zD0xQZiaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zD0xQ5iaEeuiH60Puc3mNA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zD0xRJiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zD0xRZiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zD0xRpiaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zD0xSJiaEeuiH60Puc3mNA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zD0xR5iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0yEbwZiaEeuiH60Puc3mNA">
            <targetForm xmi:type="expression:Expression" xmi:id="_pvWq0KOTEeuF1NgcLbyZ9A" name="confirmareVizita" content="38e32796-b9aa-416c-87e0-f5e90808d023" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0yEbwJiaEeuiH60Puc3mNA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0yEbw5iaEeuiH60Puc3mNA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_bQjtALDbEeuedochNpJCTQ" name="creareContCumparator" dataType="_g7sypJiTEeuiH60Puc3mNA" className="com.company.luxmob.DataModelCumparator">
        <defaultValue xmi:type="expression:Expression" xmi:id="_CPM_BbD0Eeu8woL_yyiYCQ" name="initCreareContCumparator()" content="def dataModelCumparatorVar = new com.company.luxmob.DataModelCumparator()&#xD;&#xA;dataModelCumparatorVar.mail = creareContCumparatorInput?.mail&#xD;&#xA;dataModelCumparatorVar.password = creareContCumparatorInput?.password&#xD;&#xA;dataModelCumparatorVar.nume = creareContCumparatorInput?.nume&#xD;&#xA;dataModelCumparatorVar.prenume = creareContCumparatorInput?.prenume&#xD;&#xA;dataModelCumparatorVar.telefon = creareContCumparatorInput?.telefon&#xD;&#xA;dataModelCumparatorVar.adresa = creareContCumparatorInput?.adresa&#xD;&#xA;return dataModelCumparatorVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.luxmob.DataModelCumparator">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_CPM_BrD0Eeu8woL_yyiYCQ" name="creareContCumparatorInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_g7syhJiTEeuiH60Puc3mNA">
        <targetForm xmi:type="expression:Expression" xmi:id="_r4JoB7D0Eeu8woL_yyiYCQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_g7syhpiTEeuiH60Puc3mNA">
        <targetForm xmi:type="expression:Expression" xmi:id="_g7syh5iTEeuiH60Puc3mNA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g7syiJiTEeuiH60Puc3mNA" target="_g7syd5iTEeuiH60Puc3mNA" source="_g7syc5iTEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g7syiZiTEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_g7syipiTEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PXqpEJiVEeuiH60Puc3mNA" target="_ScPNUJiVEeuiH60Puc3mNA" source="_Lv4DAJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PXqpEZiVEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PXqpEpiVEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rUgHYJiVEeuiH60Puc3mNA" target="_h62QYJiVEeuiH60Puc3mNA" source="_ScPNUJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rUgHYZiVEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_rUgucJiVEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uAksEJiVEeuiH60Puc3mNA" name="Credențiale valide" target="_wlijMJiVEeuiH60Puc3mNA" source="_h62QYJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uAlTIJiVEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_uAlTIZiVEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8Sjj8JiVEeuiH60Puc3mNA" target="_8Sc2QJiVEeuiH60Puc3mNA" source="_wlijMJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8SkLAJiVEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8SkLAZiVEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WGmw0JiWEeuiH60Puc3mNA" target="_zeHdYJiWEeuiH60Puc3mNA" source="_8Sc2QJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WGmw0ZiWEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_WGmw0piWEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YEEjEJiWEeuiH60Puc3mNA" target="_nKKYcJiWEeuiH60Puc3mNA" source="_8Sc2QJiVEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YEEjEZiWEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_YEEjEpiWEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2iM5cJiWEeuiH60Puc3mNA" target="_6DeAwJiWEeuiH60Puc3mNA" source="_g7syd5iTEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2iM5cZiWEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_2iM5cpiWEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7fi9MJiWEeuiH60Puc3mNA" target="_-vyl8JiWEeuiH60Puc3mNA" source="_6DeAwJiWEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7fi9MZiWEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_7fi9MpiWEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_I7yf4JiXEeuiH60Puc3mNA" target="_HMcpMJiXEeuiH60Puc3mNA" source="_-vyl8JiWEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_I7zG8JiXEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_I7zG8ZiXEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bIXlEJiXEeuiH60Puc3mNA" name="User nelogat" target="_tbPfgJiXEeuiH60Puc3mNA" source="_HMcpMJiXEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bIXlEZiXEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bIXlEpiXEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vIBKYJiXEeuiH60Puc3mNA" target="_23xrYJiXEeuiH60Puc3mNA" source="_tbPfgJiXEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vIBKYZiXEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_vIBKYpiXEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3tjc0JiXEeuiH60Puc3mNA" name="User-ul nu are cont" target="_E5zbsJiYEeuiH60Puc3mNA" source="_23xrYJiXEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3tkD4JiXEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3tkD4ZiXEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D6qS4JiYEeuiH60Puc3mNA" target="_JIFaAJiYEeuiH60Puc3mNA" source="_E5zbsJiYEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D6qS4ZiYEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D6qS4piYEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KM9XYJiYEeuiH60Puc3mNA" name="User-ul are cont" target="_P00XwJiYEeuiH60Puc3mNA" source="_23xrYJiXEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KM9-cJiYEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_KM9-cZiYEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZEkE0JiYEeuiH60Puc3mNA" target="_P00XwJiYEeuiH60Puc3mNA" source="_HMcpMJiXEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZEkE0ZiYEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZEkE0piYEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mwHO0JiYEeuiH60Puc3mNA" target="_NfrP4JiZEeuiH60Puc3mNA" source="_JIFaAJiYEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mwH14JiYEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_mwH14ZiYEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8PIVIJiYEeuiH60Puc3mNA" name="Formular necompletat" target="_6DeAwJiWEeuiH60Puc3mNA" source="_NfrP4JiZEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8PIVIZiYEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8PIVIpiYEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BocjMJiZEeuiH60Puc3mNA" name="Formular completat" target="_P00XwJiYEeuiH60Puc3mNA" source="_NfrP4JiZEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BocjMZiZEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BocjMpiZEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F3FG0JiZEeuiH60Puc3mNA" target="_DQqBsJiaEeuiH60Puc3mNA" source="_P00XwJiYEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F3Ft4JiZEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_F3Ft4ZiZEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Bxt-gJiaEeuiH60Puc3mNA" target="_BxpGAJiaEeuiH60Puc3mNA" source="_DQqBsJiaEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Bxt-gZiaEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Bxt-gpiaEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NomF4JiaEeuiH60Puc3mNA" target="_NohNYJiaEeuiH60Puc3mNA" source="_zeHdYJiWEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NomF4ZiaEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_NomF4piaEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PUJBsJiaEeuiH60Puc3mNA" target="_NohNYJiaEeuiH60Puc3mNA" source="_BxpGAJiaEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PUJowJiaEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PUJowZiaEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oo5DcJiaEeuiH60Puc3mNA" name="Solicitare aprobată" target="_shCZsJiaEeuiH60Puc3mNA" source="_NohNYJiaEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oo5DcZiaEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oo5DcpiaEeuiH60Puc3mNA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zD6Q0JiaEeuiH60Puc3mNA" target="_0yDNoJiaEeuiH60Puc3mNA" source="_shCZsJiaEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zD6Q0ZiaEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_zD6Q0piaEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_j0UrwJibEeuiH60Puc3mNA" target="_LM5qEJibEeuiH60Puc3mNA" source="_0yDNoJiaEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_j0UrwZibEeuiH60Puc3mNA"/>
        <condition xmi:type="expression:Expression" xmi:id="_j0UrwpibEeuiH60Puc3mNA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BcAiUJicEeuMnLTQnxFs6A" target="_Bw7CYJicEeuMnLTQnxFs6A" source="_LM5qEJibEeuiH60Puc3mNA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BcBJYJicEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_BcBJYZicEeuMnLTQnxFs6A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EMOnMJicEeuMnLTQnxFs6A" name="Decizie nefavorabilă" target="_X2mgEJicEeuMnLTQnxFs6A" source="_Bw7CYJicEeuMnLTQnxFs6A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EMPOQJicEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_EMPOQZicEeuMnLTQnxFs6A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FQqfsJicEeuMnLTQnxFs6A" name="Decizie favorabilă" target="__ZmEsJx3EeunR90isTkFuQ" source="_Bw7CYJicEeuMnLTQnxFs6A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FQqfsZicEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_FQqfspicEeuMnLTQnxFs6A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YZpiwJicEeuMnLTQnxFs6A" target="_YraoMJicEeuMnLTQnxFs6A" source="_X2mgEJicEeuMnLTQnxFs6A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YZpiwZicEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_YZpiwpicEeuMnLTQnxFs6A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_elyU4JicEeuMnLTQnxFs6A" target="_6DeAwJiWEeuiH60Puc3mNA" source="_YraoMJicEeuMnLTQnxFs6A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ely78JicEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ely78ZicEeuMnLTQnxFs6A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZvISgJidEeuMnLTQnxFs6A" target="_-01KwJx3EeunR90isTkFuQ" source="__ZmEsJx3EeunR90isTkFuQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZvISgZidEeuMnLTQnxFs6A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZvI5kJidEeuMnLTQnxFs6A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0vD0oJx3EeunR90isTkFuQ" target="_1Wnj4Jx3EeunR90isTkFuQ" source="_-01KwJx3EeunR90isTkFuQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0vD0oZx3EeunR90isTkFuQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0vD0opx3EeunR90isTkFuQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5NVWwJx3EeunR90isTkFuQ" name="Lipsă dovezi și nesemnare antecontract" target="_YraoMJicEeuMnLTQnxFs6A" source="_1Wnj4Jx3EeunR90isTkFuQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5NVWwZx3EeunR90isTkFuQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5NVWwpx3EeunR90isTkFuQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-UNxAJx3EeunR90isTkFuQ" name="Antecontract semnat și dovezi înregistrate" target="_SbwuEJx4Eeumk8Ucz-RH9A" source="_1Wnj4Jx3EeunR90isTkFuQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-UOYEJx3EeunR90isTkFuQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_-UOYEZx3EeunR90isTkFuQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_V-GzcJx4Eeumk8Ucz-RH9A" target="_WV5BUJx4Eeumk8Ucz-RH9A" source="_SbwuEJx4Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_V-GzcZx4Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_V-Gzcpx4Eeumk8Ucz-RH9A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cnuLwJx4Eeumk8Ucz-RH9A" name="Plăți invalide" target="_-01KwJx3EeunR90isTkFuQ" source="_WV5BUJx4Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cnvZ4Jx4Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_cnvZ4Zx4Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f_pJ0Jx4Eeumk8Ucz-RH9A" name="Plăți valide" target="_h3HBwJx4Eeumk8Ucz-RH9A" source="_WV5BUJx4Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f_pJ0Zx4Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_f_pJ0px4Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wX_RQJx4Eeumk8Ucz-RH9A" target="_zLt9IJx4Eeumk8Ucz-RH9A" source="_h3HBwJx4Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wX_RQZx4Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_wX_RQpx4Eeumk8Ucz-RH9A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7aIwEJx4Eeumk8Ucz-RH9A" target="_DN188Jx5Eeumk8Ucz-RH9A" source="_zLt9IJx4Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7aIwEZx4Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_7aIwEpx4Eeumk8Ucz-RH9A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DzUBgJx5Eeumk8Ucz-RH9A" target="_YraoMJicEeuMnLTQnxFs6A" source="_DN188Jx5Eeumk8Ucz-RH9A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DzVPoJx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_DzVPoZx5Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KEr48Jx5Eeumk8Ucz-RH9A" name="Contract semnat și plată înregistrată" target="_N7EUoJx5Eeumk8Ucz-RH9A" source="_DN188Jx5Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KEr48Zx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_KEr48px5Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dsipUJx5Eeumk8Ucz-RH9A" target="_gdBM4Jx5Eeumk8Ucz-RH9A" source="_N7EUoJx5Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dsipUZx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_dsipUpx5Eeumk8Ucz-RH9A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hqGEAJx5Eeumk8Ucz-RH9A" name="Plată validă" target="_hqAkcJx5Eeumk8Ucz-RH9A" source="_gdBM4Jx5Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hqGEAZx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_hqGrEJx5Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rRp0IJx5Eeumk8Ucz-RH9A" name="Plată invalidă" target="_YraoMJicEeuMnLTQnxFs6A" source="_gdBM4Jx5Eeumk8Ucz-RH9A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rRp0IZx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_rRp0Ipx5Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xXns0Jx5Eeumk8Ucz-RH9A" target="_usoGMJx5Eeumk8Ucz-RH9A" source="_hqAkcJx5Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xXns0Zx5Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_xXns0px5Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DUTNcJx9Eeumk8Ucz-RH9A" target="_DUMfwJx9Eeumk8Ucz-RH9A" source="_gdBM4Jx5Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DUTNcZx9Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_DUTNcpx9Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DpI1AJx9Eeumk8Ucz-RH9A" target="_usoGMJx5Eeumk8Ucz-RH9A" source="_DUMfwJx9Eeumk8Ucz-RH9A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DpI1AZx9Eeumk8Ucz-RH9A"/>
        <condition xmi:type="expression:Expression" xmi:id="_DpI1Apx9Eeumk8Ucz-RH9A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_zX-ggJiTEeuiH60Puc3mNA" documentation="Persoana care dorește să achiziționeze un imobil." name="Cumpărător" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_5zfycJiTEeuiH60Puc3mNA" documentation="Persoana care intermediază procesul de vânzare al unui imobil." name="Agent imobiliar"/>
      <contract xmi:type="process:Contract" xmi:id="_g7syjJiTEeuiH60Puc3mNA">
        <inputs xmi:type="process:ContractInput" xmi:id="_CPMX8LD0Eeu8woL_yyiYCQ" name="creareContCumparatorInput" type="COMPLEX" dataReference="creareContCumparator">
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX8bD0Eeu8woL_yyiYCQ" name="mail"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX8rD0Eeu8woL_yyiYCQ" name="password"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX87D0Eeu8woL_yyiYCQ" name="nume"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX9LD0Eeu8woL_yyiYCQ" name="prenume"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX9bD0Eeu8woL_yyiYCQ" name="telefon"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_CPMX9rD0Eeu8woL_yyiYCQ" name="adresa"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_CPM_ALD0Eeu8woL_yyiYCQ" expression="creareContCumparatorInput?.mail != null" errorMessage="mail is mandatory for DataModelCumparator" name="mandatory_creareContCumparatorInput_mail">
          <inputNames>creareContCumparatorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_CPM_AbD0Eeu8woL_yyiYCQ" expression="creareContCumparatorInput?.password != null" errorMessage="password is mandatory for DataModelCumparator" name="mandatory_creareContCumparatorInput_password">
          <inputNames>creareContCumparatorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_CPM_ArD0Eeu8woL_yyiYCQ" expression="creareContCumparatorInput?.nume != null" errorMessage="nume is mandatory for DataModelCumparator" name="mandatory_creareContCumparatorInput_nume">
          <inputNames>creareContCumparatorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_CPM_A7D0Eeu8woL_yyiYCQ" expression="creareContCumparatorInput?.prenume != null" errorMessage="prenume is mandatory for DataModelCumparator" name="mandatory_creareContCumparatorInput_prenume">
          <inputNames>creareContCumparatorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_CPM_BLD0Eeu8woL_yyiYCQ" expression="creareContCumparatorInput?.telefon != null" errorMessage="telefon is mandatory for DataModelCumparator" name="mandatory_creareContCumparatorInput_telefon">
          <inputNames>creareContCumparatorInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g7syjZiTEeuiH60Puc3mNA">
        <name xmi:type="expression:Expression" xmi:id="_g7syjpiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g7syj5iTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g7sykJiTEeuiH60Puc3mNA">
        <name xmi:type="expression:Expression" xmi:id="_g7sykZiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g7sykpiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g7syk5iTEeuiH60Puc3mNA">
        <name xmi:type="expression:Expression" xmi:id="_g7sylJiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g7sylZiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g7sylpiTEeuiH60Puc3mNA">
        <name xmi:type="expression:Expression" xmi:id="_g7syl5iTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g7symJiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g7symZiTEeuiH60Puc3mNA">
        <name xmi:type="expression:Expression" xmi:id="_g7sympiTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g7sym5iTEeuiH60Puc3mNA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_g7synJiTEeuiH60Puc3mNA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_g7synZiTEeuiH60Puc3mNA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_g7synpiTEeuiH60Puc3mNA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_g7syn5iTEeuiH60Puc3mNA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_g7syoJiTEeuiH60Puc3mNA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_g7syoZiTEeuiH60Puc3mNA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_g7syopiTEeuiH60Puc3mNA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_g7syo5iTEeuiH60Puc3mNA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_g7sypJiTEeuiH60Puc3mNA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_g7sypZiTEeuiH60Puc3mNA" type="Process" element="_g7sycJiTEeuiH60Puc3mNA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_g7tZgJiTEeuiH60Puc3mNA" type="2007" element="_g7sycZiTEeuiH60Puc3mNA">
      <children xmi:type="notation:DecorationNode" xmi:id="_g7tZgZiTEeuiH60Puc3mNA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_g7tZgpiTEeuiH60Puc3mNA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_g7tZg5iTEeuiH60Puc3mNA" type="3007" element="_g7sycpiTEeuiH60Puc3mNA">
          <children xmi:type="notation:DecorationNode" xmi:id="_g7tZhJiTEeuiH60Puc3mNA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_g7tZhZiTEeuiH60Puc3mNA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_g7tZhpiTEeuiH60Puc3mNA" type="3005" element="_g7syd5iTEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_g7tZh5iTEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g7tZiJiTEeuiH60Puc3mNA" x="245" y="90" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_g7tZiZiTEeuiH60Puc3mNA" type="3002" element="_g7syc5iTEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_g7tZipiTEeuiH60Puc3mNA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_g7tZi5iTEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g7tZjJiTEeuiH60Puc3mNA" x="106" y="98"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6DfO65iWEeuiH60Puc3mNA" type="3005" element="_6DeAwJiWEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6Df18JiWEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6DfO7JiWEeuiH60Puc3mNA" x="470" y="87" width="139" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-vzNAJiWEeuiH60Puc3mNA" type="3005" element="_-vyl8JiWEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-vzNApiWEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-vzNAZiWEeuiH60Puc3mNA" x="718" y="88" width="135" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HMd3UJiXEeuiH60Puc3mNA" type="3051" element="_HMcpMJiXEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HMeeYJiXEeuiH60Puc3mNA" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HMeeYZiXEeuiH60Puc3mNA" x="95" y="-10"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HMd3UZiXEeuiH60Puc3mNA" x="764" y="210"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tbQGmJiXEeuiH60Puc3mNA" type="3028" element="_tbPfgJiXEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tbQGmpiXEeuiH60Puc3mNA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tbQGmZiXEeuiH60Puc3mNA" x="707" y="336" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_23ySc5iXEeuiH60Puc3mNA" type="3051" element="_23xrYJiXEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_23ySdZiXEeuiH60Puc3mNA" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_23ySdpiXEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_23ySdJiXEeuiH60Puc3mNA" x="1022" y="358" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_E51Q4JiYEeuiH60Puc3mNA" type="3028" element="_E5zbsJiYEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_E51Q4piYEeuiH60Puc3mNA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_E51Q4ZiYEeuiH60Puc3mNA" x="963" y="162" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JIGBEJiYEeuiH60Puc3mNA" type="3005" element="_JIFaAJiYEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JIGBEpiYEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JIGBEZiYEeuiH60Puc3mNA" x="995" y="64" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_P00-2ZiYEeuiH60Puc3mNA" type="3005" element="_P00XwJiYEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_P00-25iYEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_P00-2piYEeuiH60Puc3mNA" x="1190" y="349" width="123" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Nfr285iZEeuiH60Puc3mNA" type="3051" element="_NfrP4JiZEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NfseAJiZEeuiH60Puc3mNA" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NfseAZiZEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Nfr29JiZEeuiH60Puc3mNA" x="1228" y="68" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BxqUIJiaEeuiH60Puc3mNA" type="3027" element="_BxpGAJiaEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BxqUIpiaEeuiH60Puc3mNA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BxqUIZiaEeuiH60Puc3mNA" x="1406" y="474" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DQqozJiaEeuiH60Puc3mNA" type="3005" element="_DQqBsJiaEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DQrP0JiaEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DQqozZiaEeuiH60Puc3mNA" x="1382" y="223" width="133" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LM64MJibEeuiH60Puc3mNA" type="3017" element="_LM5qEJibEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LM64MpibEeuiH60Puc3mNA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LM64M5ibEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LM64MZibEeuiH60Puc3mNA" x="1886" y="546"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Bw8QgJicEeuMnLTQnxFs6A" type="3051" element="_Bw7CYJicEeuMnLTQnxFs6A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Bw8QgpicEeuMnLTQnxFs6A" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Bw8Qg5icEeuMnLTQnxFs6A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Bw8QgZicEeuMnLTQnxFs6A" x="1997" y="543" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_X2nuMJicEeuMnLTQnxFs6A" type="3027" element="_X2mgEJicEeuMnLTQnxFs6A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_X2nuMpicEeuMnLTQnxFs6A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_X2nuMZicEeuMnLTQnxFs6A" x="1957" y="349" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YrbPRJicEeuMnLTQnxFs6A" type="3028" element="_YraoMJicEeuMnLTQnxFs6A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_YrbPRpicEeuMnLTQnxFs6A" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YrbPRZicEeuMnLTQnxFs6A" x="1942" y="210" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1WoyAJx3EeunR90isTkFuQ" type="3051" element="_1Wnj4Jx3EeunR90isTkFuQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1WoyApx3EeunR90isTkFuQ" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1WoyA5x3EeunR90isTkFuQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1WoyAZx3EeunR90isTkFuQ" x="2329" y="577" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-01x3Jx3EeunR90isTkFuQ" type="3005" element="_-01KwJx3EeunR90isTkFuQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-02Y4Jx3EeunR90isTkFuQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-01x3Zx3EeunR90isTkFuQ" x="2113" y="526" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zLukPJx4Eeumk8Ucz-RH9A" type="3005" element="_zLt9IJx4Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zLvLQJx4Eeumk8Ucz-RH9A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zLukPZx4Eeumk8Ucz-RH9A" x="2569" y="526" width="172" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DN3yI5x5Eeumk8Ucz-RH9A" type="3051" element="_DN188Jx5Eeumk8Ucz-RH9A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_DN4ZMJx5Eeumk8Ucz-RH9A" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_DN4ZMZx5Eeumk8Ucz-RH9A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DN3yJJx5Eeumk8Ucz-RH9A" x="2830" y="545" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_DUPjEJx9Eeumk8Ucz-RH9A" type="3027" element="_DUMfwJx9Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_DUPjEpx9Eeumk8Ucz-RH9A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DUPjEZx9Eeumk8Ucz-RH9A" x="3120" y="592" width="158" height="79"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_g7tZjZiTEeuiH60Puc3mNA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_g7tZjpiTEeuiH60Puc3mNA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_g7tZj5iTEeuiH60Puc3mNA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_g7tZkJiTEeuiH60Puc3mNA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g7tZkZiTEeuiH60Puc3mNA" x="23" y="10" width="3512" height="715"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_vplGsJiUEeuiH60Puc3mNA" type="3007" element="_vpjRgJiUEeuiH60Puc3mNA">
          <children xmi:type="notation:DecorationNode" xmi:id="_vpltwJiUEeuiH60Puc3mNA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vpltwZiUEeuiH60Puc3mNA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Lv54MJiVEeuiH60Puc3mNA" type="3002" element="_Lv4DAJiVEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Lv54MpiVEeuiH60Puc3mNA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Lv54M5iVEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Lv54MZiVEeuiH60Puc3mNA" x="86" y="160"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ScRpkJiVEeuiH60Puc3mNA" type="3005" element="_ScPNUJiVEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ScRpkpiVEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ScRpkZiVEeuiH60Puc3mNA" x="238" y="137" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h623cJiVEeuiH60Puc3mNA" type="3051" element="_h62QYJiVEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_h63egJiVEeuiH60Puc3mNA" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_h63egZiVEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h623cZiVEeuiH60Puc3mNA" x="470" y="153"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wljxUJiVEeuiH60Puc3mNA" type="3028" element="_wlijMJiVEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wljxUpiVEeuiH60Puc3mNA" type="5018"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wljxUZiVEeuiH60Puc3mNA" x="518" y="292" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8SercJiVEeuiH60Puc3mNA" type="3009" element="_8Sc2QJiVEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8SfSgJiVEeuiH60Puc3mNA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8SfSgZiVEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8SercZiVEeuiH60Puc3mNA" x="782" y="309"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nKK_jJiWEeuiH60Puc3mNA" type="3005" element="_nKKYcJiWEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nKK_jpiWEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nKK_jZiWEeuiH60Puc3mNA" x="718" y="436" width="172" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zeIrgJiWEeuiH60Puc3mNA" type="3005" element="_zeHdYJiWEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zeIrgpiWEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zeIrgZiWEeuiH60Puc3mNA" x="708" y="127" width="192" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NoibgJiaEeuiH60Puc3mNA" type="3009" element="_NohNYJiaEeuiH60Puc3mNA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NoibgpiaEeuiH60Puc3mNA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Noibg5iaEeuiH60Puc3mNA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NoibgZiaEeuiH60Puc3mNA" x="1046" y="152"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_shDn2JiaEeuiH60Puc3mNA" type="3005" element="_shCZsJiaEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_shEO4JiaEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_shDn2ZiaEeuiH60Puc3mNA" x="1233" y="53" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__ZmrwJx3EeunR90isTkFuQ" type="3005" element="__ZmEsJx3EeunR90isTkFuQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__Zmrwpx3EeunR90isTkFuQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__ZmrwZx3EeunR90isTkFuQ" x="1940" y="111" width="158" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Sb_XkJx4Eeumk8Ucz-RH9A" type="3005" element="_SbwuEJx4Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Sb_Xkpx4Eeumk8Ucz-RH9A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Sb_XkZx4Eeumk8Ucz-RH9A" x="2252" y="92" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WV5oY5x4Eeumk8Ucz-RH9A" type="3051" element="_WV5BUJx4Eeumk8Ucz-RH9A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WV5oZZx4Eeumk8Ucz-RH9A" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WV6PcJx4Eeumk8Ucz-RH9A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WV5oZJx4Eeumk8Ucz-RH9A" x="2482" y="96" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h3KFG5x4Eeumk8Ucz-RH9A" type="3005" element="_h3HBwJx4Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h3KFHZx4Eeumk8Ucz-RH9A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h3KFHJx4Eeumk8Ucz-RH9A" x="2607" y="93" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_N7E7uZx5Eeumk8Ucz-RH9A" type="3005" element="_N7EUoJx5Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_N7E7u5x5Eeumk8Ucz-RH9A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_N7E7upx5Eeumk8Ucz-RH9A" x="2781" y="91" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gdBM5Jx5Eeumk8Ucz-RH9A" type="3051" element="_gdBM4Jx5Eeumk8Ucz-RH9A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_gdBz8Jx5Eeumk8Ucz-RH9A" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gdBz8Zx5Eeumk8Ucz-RH9A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gdBM5Zx5Eeumk8Ucz-RH9A" x="2987" y="98" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hqDAsJx5Eeumk8Ucz-RH9A" type="3027" element="_hqAkcJx5Eeumk8Ucz-RH9A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_hqDAspx5Eeumk8Ucz-RH9A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hqDAsZx5Eeumk8Ucz-RH9A" x="3139" y="97" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_usqicJx5Eeumk8Ucz-RH9A" type="3003" element="_usoGMJx5Eeumk8Ucz-RH9A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_usqicpx5Eeumk8Ucz-RH9A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_usqic5x5Eeumk8Ucz-RH9A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_usqicZx5Eeumk8Ucz-RH9A" x="3372" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0yEbxJiaEeuiH60Puc3mNA" type="3005" element="_0yDNoJiaEeuiH60Puc3mNA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0yFC0JiaEeuiH60Puc3mNA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0yEbxZiaEeuiH60Puc3mNA" x="1619" y="42" width="126" height="63"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vplGsZiUEeuiH60Puc3mNA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vplGspiUEeuiH60Puc3mNA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vplGs5iUEeuiH60Puc3mNA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vpltwpiUEeuiH60Puc3mNA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vplGtJiUEeuiH60Puc3mNA" x="53" y="350" width="1922" height="582"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_g7tZkpiTEeuiH60Puc3mNA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_g7tZk5iTEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_g7tZlJiTEeuiH60Puc3mNA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_g7tZlZiTEeuiH60Puc3mNA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g7tZlpiTEeuiH60Puc3mNA" width="3535" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_g7tZl5iTEeuiH60Puc3mNA"/>
    <edges xmi:type="notation:Connector" xmi:id="_g7tZmJiTEeuiH60Puc3mNA" type="4001" element="_g7syiJiTEeuiH60Puc3mNA" source="_g7tZiZiTEeuiH60Puc3mNA" target="_g7tZhpiTEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g7tZmZiTEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g7tZmpiTEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g7tZm5iTEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g7tZnJiTEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PXr3MJiVEeuiH60Puc3mNA" type="4001" element="_PXqpEJiVEeuiH60Puc3mNA" source="_Lv54MJiVEeuiH60Puc3mNA" target="_ScRpkJiVEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PXseQJiVEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PXseQZiVEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PXr3MZiVEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PXr3MpiVEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rUgucZiVEeuiH60Puc3mNA" type="4001" element="_rUgHYJiVEeuiH60Puc3mNA" source="_ScRpkJiVEeuiH60Puc3mNA" target="_h623cJiVEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rUhVgpiVEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rUhVg5iVEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rUhVgJiVEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rUhVgZiVEeuiH60Puc3mNA" points="[0, 0, -127, -9]$[130, 28, 3, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rUjKsJiVEeuiH60Puc3mNA" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uAl6MJiVEeuiH60Puc3mNA" type="4001" element="_uAksEJiVEeuiH60Puc3mNA" source="_h623cJiVEeuiH60Puc3mNA" target="_wljxUJiVEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uAmhQJiVEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uAmhQZiVEeuiH60Puc3mNA" x="-19" y="36"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uAl6MZiVEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uAl6MpiVEeuiH60Puc3mNA" points="[22, 0, -82, -156]$[123, 0, 19, -156]$[123, 118, 19, -38]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8SkyEJiVEeuiH60Puc3mNA" type="4001" element="_8Sjj8JiVEeuiH60Puc3mNA" source="_wljxUJiVEeuiH60Puc3mNA" target="_8SercJiVEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8SkyE5iVEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8SkyFJiVEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8SkyEZiVEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8SkyEpiVEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WGnX4JiWEeuiH60Puc3mNA" type="4001" element="_WGmw0JiWEeuiH60Puc3mNA" source="_8SercJiVEeuiH60Puc3mNA" target="_zeIrgJiWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WGn-8JiWEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WGn-8ZiWEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WGnX4ZiWEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WGnX4piWEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YEFKIJiWEeuiH60Puc3mNA" type="4001" element="_YEEjEJiWEeuiH60Puc3mNA" source="_8SercJiVEeuiH60Puc3mNA" target="_nKK_jJiWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YEFxMJiWEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YEFxMZiWEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YEFKIZiWEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YEFKIpiWEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2iNggJiWEeuiH60Puc3mNA" type="4001" element="_2iM5cJiWEeuiH60Puc3mNA" source="_g7tZhpiTEeuiH60Puc3mNA" target="_6DfO65iWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2iNgg5iWEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2iNghJiWEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2iNggZiWEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2iNggpiWEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7fjkQJiWEeuiH60Puc3mNA" type="4001" element="_7fi9MJiWEeuiH60Puc3mNA" source="_6DfO65iWEeuiH60Puc3mNA" target="_-vzNAJiWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7fjkQ5iWEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7fjkRJiWEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7fjkQZiWEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7fjkQpiWEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_I7zG8piXEeuiH60Puc3mNA" type="4001" element="_I7yf4JiXEeuiH60Puc3mNA" source="_-vzNAJiWEeuiH60Puc3mNA" target="_HMd3UJiXEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_I7zuAJiXEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_I7zuAZiXEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_I7zG85iXEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_I7zG9JiXEeuiH60Puc3mNA" points="[-68, 37, 0, -76]$[-68, 92, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_I708IJiXEeuiH60Puc3mNA" id="(1.0,0.44776119402985076)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bIXlE5iXEeuiH60Puc3mNA" type="4001" element="_bIXlEJiXEeuiH60Puc3mNA" source="_HMd3UJiXEeuiH60Puc3mNA" target="_tbQGmJiXEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bIYMIJiXEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bIYMIZiXEeuiH60Puc3mNA" x="22" y="46"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bIXlFJiXEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bIXlFZiXEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vIBxcJiXEeuiH60Puc3mNA" type="4001" element="_vIBKYJiXEeuiH60Puc3mNA" source="_tbQGmJiXEeuiH60Puc3mNA" target="_23ySc5iXEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vIBxc5iXEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vIBxdJiXEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vIBxcZiXEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vIBxcpiXEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3tkD4piXEeuiH60Puc3mNA" type="4001" element="_3tjc0JiXEeuiH60Puc3mNA" source="_23ySc5iXEeuiH60Puc3mNA" target="_E51Q4JiYEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3tkq8JiXEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3tkq8ZiXEeuiH60Puc3mNA" x="-8" y="-55"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3tkD45iXEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3tkD5JiXEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D6q58JiYEeuiH60Puc3mNA" type="4001" element="_D6qS4JiYEeuiH60Puc3mNA" source="_E51Q4JiYEeuiH60Puc3mNA" target="_JIGBEJiYEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D6q585iYEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D6q59JiYEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D6q58ZiYEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D6q58piYEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KM-lgJiYEeuiH60Puc3mNA" type="4001" element="_KM9XYJiYEeuiH60Puc3mNA" source="_23ySc5iXEeuiH60Puc3mNA" target="_P00-2ZiYEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KM-lg5iYEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KM-lhJiYEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KM-lgZiYEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KM-lgpiYEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZEkr4JiYEeuiH60Puc3mNA" type="4001" element="_ZEkE0JiYEeuiH60Puc3mNA" source="_HMd3UJiXEeuiH60Puc3mNA" target="_P00-2ZiYEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZEkr45iYEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZEkr5JiYEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZEkr4ZiYEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZEkr4piYEeuiH60Puc3mNA" points="[-43, -14, -525, -165]$[-169, -14, -651, -165]$[-169, 205, -651, 54]$[444, 205, -38, 54]$[444, 165, -38, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZEmhEJiYEeuiH60Puc3mNA" id="(1.0,0.813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZEmhEZiYEeuiH60Puc3mNA" id="(0.8048780487804879,0.7704918032786885)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mwH14piYEeuiH60Puc3mNA" type="4001" element="_mwHO0JiYEeuiH60Puc3mNA" source="_JIGBEJiYEeuiH60Puc3mNA" target="_Nfr285iZEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mwIc8JiYEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mwIc8ZiYEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mwH145iYEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mwH15JiYEeuiH60Puc3mNA" points="[0, -5, -116, 4]$[110, 6, -6, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mwJrEJiYEeuiH60Puc3mNA" id="(1.0,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8PLYcJiYEeuiH60Puc3mNA" type="4001" element="_8PIVIJiYEeuiH60Puc3mNA" source="_Nfr285iZEeuiH60Puc3mNA" target="_6DfO65iWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8PLYc5iYEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8PLYdJiYEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8PLYcZiYEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8PLYcpiYEeuiH60Puc3mNA" points="[-22, -31, 710, -53]$[-22, -57, 710, -79]$[-720, -57, 12, -79]$[-720, -12, 12, -34]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8PMmkJiYEeuiH60Puc3mNA" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BokfAJiZEeuiH60Puc3mNA" type="4001" element="_BocjMJiZEeuiH60Puc3mNA" source="_Nfr285iZEeuiH60Puc3mNA" target="_P00-2ZiYEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BolGEJiZEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BolGEZiZEeuiH60Puc3mNA" x="-10" y="-31"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BokfAZiZEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BokfApiZEeuiH60Puc3mNA" points="[-22, 13, 2, -245]$[-26, 251, -2, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Bom7QJiZEeuiH60Puc3mNA" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Bom7QZiZEeuiH60Puc3mNA" id="(0.4634146341463415,0.11475409836065574)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F3GU8JiZEeuiH60Puc3mNA" type="4001" element="_F3FG0JiZEeuiH60Puc3mNA" source="_P00-2ZiYEeuiH60Puc3mNA" target="_DQqozJiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F3GU85iZEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F3GU9JiZEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F3GU8ZiZEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F3GU8piZEeuiH60Puc3mNA" points="[62, 0, -145, 131]$[203, 0, -4, 131]$[203, -106, -4, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BxulkJiaEeuiH60Puc3mNA" type="4001" element="_Bxt-gJiaEeuiH60Puc3mNA" source="_DQqozJiaEeuiH60Puc3mNA" target="_BxqUIJiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Bxulk5iaEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BxullJiaEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BxulkZiaEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BxulkpiaEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Noms8JiaEeuiH60Puc3mNA" type="4001" element="_NomF4JiaEeuiH60Puc3mNA" source="_zeIrgJiWEeuiH60Puc3mNA" target="_NoibgJiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Noms85iaEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Noms9JiaEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Noms8ZiaEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Noms8piaEeuiH60Puc3mNA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PUKP0JiaEeuiH60Puc3mNA" type="4001" element="_PUJBsJiaEeuiH60Puc3mNA" source="_BxqUIJiaEeuiH60Puc3mNA" target="_NoibgJiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PUKP05iaEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PUKP1JiaEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PUKP0ZiaEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PUKP0piaEeuiH60Puc3mNA" points="[-154, 6, 339, -275]$[-496, 6, -3, -275]$[-496, 263, -3, -18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_PULd8JiaEeuiH60Puc3mNA" id="(1.0,0.37662337662337664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oo64oJiaEeuiH60Puc3mNA" type="4001" element="_oo5DcJiaEeuiH60Puc3mNA" source="_NoibgJiaEeuiH60Puc3mNA" target="_shDn2JiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oo64o5iaEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oo7fsJiaEeuiH60Puc3mNA" x="13" y="-6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oo64oZiaEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oo64opiaEeuiH60Puc3mNA" points="[13, -8, -148, 78]$[51, -8, -110, 78]$[51, -87, -110, -1]$[111, -87, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zD6Q05iaEeuiH60Puc3mNA" type="4001" element="_zD6Q0JiaEeuiH60Puc3mNA" source="_shDn2JiaEeuiH60Puc3mNA" target="_0yEbxJiaEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zD634JiaEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zD634ZiaEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zD6Q1JiaEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zD6Q1ZiaEeuiH60Puc3mNA" points="[75, -19, -351, -2]$[363, -19, -63, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_j0VS0JibEeuiH60Puc3mNA" type="4001" element="_j0UrwJibEeuiH60Puc3mNA" source="_0yEbxJiaEeuiH60Puc3mNA" target="_LM64MJibEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_j0VS05ibEeuiH60Puc3mNA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_j0VS1JibEeuiH60Puc3mNA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_j0VS0ZibEeuiH60Puc3mNA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_j0VS0pibEeuiH60Puc3mNA" points="[0, 1, -97, 0]$[90, 2, -7, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j0XIAJibEeuiH60Puc3mNA" id="(1.0,0.5079365079365079)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_j0XIAZibEeuiH60Puc3mNA" id="(0.23333333333333334,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BcEMsJicEeuMnLTQnxFs6A" type="4001" element="_BcAiUJicEeuMnLTQnxFs6A" source="_LM64MJibEeuiH60Puc3mNA" target="_Bw8QgJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BcEzwJicEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BcFa0JicEeuMnLTQnxFs6A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BcEMsZicEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BcEMspicEeuMnLTQnxFs6A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EMQcYJicEeuMnLTQnxFs6A" type="4001" element="_EMOnMJicEeuMnLTQnxFs6A" source="_Bw8QgJicEeuMnLTQnxFs6A" target="_X2nuMJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EMQcY5icEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EMQcZJicEeuMnLTQnxFs6A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EMQcYZicEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EMQcYpicEeuMnLTQnxFs6A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FQrt0JicEeuMnLTQnxFs6A" type="4001" element="_FQqfsJicEeuMnLTQnxFs6A" source="_Bw8QgJicEeuMnLTQnxFs6A" target="__ZmrwJx3EeunR90isTkFuQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FQrt05icEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FQsU4JicEeuMnLTQnxFs6A" x="16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FQrt0ZicEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FQrt0picEeuMnLTQnxFs6A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YZqJ0JicEeuMnLTQnxFs6A" type="4001" element="_YZpiwJicEeuMnLTQnxFs6A" source="_X2nuMJicEeuMnLTQnxFs6A" target="_YrbPRJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YZqw4ZicEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YZqw4picEeuMnLTQnxFs6A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YZqJ0ZicEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YZqw4JicEeuMnLTQnxFs6A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_el0xIJicEeuMnLTQnxFs6A" type="4001" element="_elyU4JicEeuMnLTQnxFs6A" source="_YrbPRJicEeuMnLTQnxFs6A" target="_6DfO65iWEeuiH60Puc3mNA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_el0xI5icEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_el0xJJicEeuMnLTQnxFs6A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_el0xIZicEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_el0xIpicEeuMnLTQnxFs6A" points="[-77, -32, 1507, 119]$[-77, -224, 1507, -73]$[-1555, -224, 29, -73]$[-1555, -155, 29, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_el3NYJicEeuMnLTQnxFs6A" id="(1.0,0.42105263157894735)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_el3NYZicEeuMnLTQnxFs6A" id="(0.28776978417266186,0.057971014492753624)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZvI5kZidEeuMnLTQnxFs6A" type="4001" element="_ZvISgJidEeuMnLTQnxFs6A" source="__ZmrwJx3EeunR90isTkFuQ" target="_-01x3Jx3EeunR90isTkFuQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZvJgoJidEeuMnLTQnxFs6A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZvJgoZidEeuMnLTQnxFs6A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZvI5kpidEeuMnLTQnxFs6A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZvI5k5idEeuMnLTQnxFs6A" points="[79, 0, -252, 241]$[323, 0, -8, 241]$[323, -216, -8, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0vFCwJx3EeunR90isTkFuQ" type="4001" element="_0vD0oJx3EeunR90isTkFuQ" source="_-01x3Jx3EeunR90isTkFuQ" target="_1WoyAJx3EeunR90isTkFuQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0vFCw5x3EeunR90isTkFuQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0vFp0Jx3EeunR90isTkFuQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0vFCwZx3EeunR90isTkFuQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0vFCwpx3EeunR90isTkFuQ" points="[70, 35, -97, -2]$[148, 35, -19, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__8EkoKOTEeuF1NgcLbyZ9A" id="(0.9857142857142858,0.7714285714285715)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5NV90Jx3EeunR90isTkFuQ" type="4001" element="_5NVWwJx3EeunR90isTkFuQ" source="_1WoyAJx3EeunR90isTkFuQ" target="_YrbPRJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5NV905x3EeunR90isTkFuQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5NV91Jx3EeunR90isTkFuQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5NV90Zx3EeunR90isTkFuQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5NV90px3EeunR90isTkFuQ" points="[-22, -30, 280, 290]$[-22, -297, 280, 23]$[-278, -297, 24, 23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5NXzAJx3EeunR90isTkFuQ" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5NXzAZx3EeunR90isTkFuQ" id="(0.8421052631578947,0.4473684210526316)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-UOYEpx3EeunR90isTkFuQ" type="4001" element="_-UNxAJx3EeunR90isTkFuQ" source="_1WoyAJx3EeunR90isTkFuQ" target="_Sb_XkJx4Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-UO_IJx3EeunR90isTkFuQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-UO_IZx3EeunR90isTkFuQ" x="29" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-UOYE5x3EeunR90isTkFuQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-UOYFJx3EeunR90isTkFuQ" points="[0, 22, 38, -185]$[0, 177, 38, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_V-IBkJx4Eeumk8Ucz-RH9A" type="4001" element="_V-GzcJx4Eeumk8Ucz-RH9A" source="_Sb_XkJx4Eeumk8Ucz-RH9A" target="_WV5oY5x4Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_V-IooJx4Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_V-IooZx4Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_V-IBkZx4Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_V-IBkpx4Eeumk8Ucz-RH9A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cnwoAJx4Eeumk8Ucz-RH9A" type="4001" element="_cnuLwJx4Eeumk8Ucz-RH9A" source="_WV5oY5x4Eeumk8Ucz-RH9A" target="_-01x3Jx3EeunR90isTkFuQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cnwoA5x4Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cnwoBJx4Eeumk8Ucz-RH9A" x="-9" y="-17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cnwoAZx4Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cnwoApx4Eeumk8Ucz-RH9A" points="[-22, -28, 293, 221]$[-22, -300, 293, -51]$[-272, -300, 43, -51]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cnydMJx4Eeumk8Ucz-RH9A" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cnydMZx4Eeumk8Ucz-RH9A" id="(0.6928571428571428,0.9142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f_pw4Jx4Eeumk8Ucz-RH9A" type="4001" element="_f_pJ0Jx4Eeumk8Ucz-RH9A" source="_WV5oY5x4Eeumk8Ucz-RH9A" target="_h3KFG5x4Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f_pw45x4Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f_qX8Jx4Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f_pw4Zx4Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f_pw4px4Eeumk8Ucz-RH9A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wX_RQ5x4Eeumk8Ucz-RH9A" type="4001" element="_wX_RQJx4Eeumk8Ucz-RH9A" source="_h3KFG5x4Eeumk8Ucz-RH9A" target="_zLukPJx4Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wX_4Upx4Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wX_4U5x4Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wX_4UJx4Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wX_4UZx4Eeumk8Ucz-RH9A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7aJXIJx4Eeumk8Ucz-RH9A" type="4001" element="_7aIwEJx4Eeumk8Ucz-RH9A" source="_zLukPJx4Eeumk8Ucz-RH9A" target="_DN3yI5x5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7aJXI5x4Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7aJXJJx4Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7aJXIZx4Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7aJXIpx4Eeumk8Ucz-RH9A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DzWdwJx5Eeumk8Ucz-RH9A" type="4001" element="_DzUBgJx5Eeumk8Ucz-RH9A" source="_DN3yI5x5Eeumk8Ucz-RH9A" target="_YrbPRJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DzWdw5x5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DzWdxJx5Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DzWdwZx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DzWdwpx5Eeumk8Ucz-RH9A" points="[-22, -30, 779, 320]$[-22, -328, 779, 22]$[-779, -328, 22, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DzXr4Jx5Eeumk8Ucz-RH9A" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DzXr4Zx5Eeumk8Ucz-RH9A" id="(0.8552631578947368,0.19736842105263158)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KEsgAJx5Eeumk8Ucz-RH9A" type="4001" element="_KEr48Jx5Eeumk8Ucz-RH9A" source="_DN3yI5x5Eeumk8Ucz-RH9A" target="_N7E7uZx5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KEsgA5x5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KEsgBJx5Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KEsgAZx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KEsgApx5Eeumk8Ucz-RH9A" points="[0, 22, 10, -205]$[0, 197, 10, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dsipU5x5Eeumk8Ucz-RH9A" type="4001" element="_dsipUJx5Eeumk8Ucz-RH9A" source="_N7E7uZx5Eeumk8Ucz-RH9A" target="_gdBM5Jx5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dsjQYJx5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dsjQYZx5Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dsipVJx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dsipVZx5Eeumk8Ucz-RH9A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hqGrEZx5Eeumk8Ucz-RH9A" type="4001" element="_hqGEAJx5Eeumk8Ucz-RH9A" source="_gdBM5Jx5Eeumk8Ucz-RH9A" target="_hqDAsJx5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hqGrFJx5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hqGrFZx5Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hqGrEpx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hqGrE5x5Eeumk8Ucz-RH9A" points="[22, 0, -169, -8]$[131, 0, -60, -8]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rRqbMJx5Eeumk8Ucz-RH9A" type="4001" element="_rRp0IJx5Eeumk8Ucz-RH9A" source="_gdBM5Jx5Eeumk8Ucz-RH9A" target="_YrbPRJicEeuMnLTQnxFs6A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rRqbM5x5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rRqbNJx5Eeumk8Ucz-RH9A" x="-183" y="-45"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rRqbMZx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rRqbMpx5Eeumk8Ucz-RH9A" points="[-22, -28, 935, 549]$[-22, -565, 935, 12]$[-936, -565, 21, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rRrpUJx5Eeumk8Ucz-RH9A" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rRrpUZx5Eeumk8Ucz-RH9A" id="(0.8618421052631579,0.14473684210526316)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xXoT4Jx5Eeumk8Ucz-RH9A" type="4001" element="_xXns0Jx5Eeumk8Ucz-RH9A" source="_hqDAsJx5Eeumk8Ucz-RH9A" target="_usqicJx5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xXoT45x5Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xXoT5Jx5Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xXoT4Zx5Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xXoT4px5Eeumk8Ucz-RH9A" points="[0, -3, -116, 4]$[113, -3, -3, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xXpiAJx5Eeumk8Ucz-RH9A" id="(1.0,0.45)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xXpiAZx5Eeumk8Ucz-RH9A" id="(0.1,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DUT0gJx9Eeumk8Ucz-RH9A" type="4001" element="_DUTNcJx9Eeumk8Ucz-RH9A" source="_gdBM5Jx5Eeumk8Ucz-RH9A" target="_DUPjEJx9Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DUT0g5x9Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DUUbkJx9Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DUT0gZx9Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DUT0gpx9Eeumk8Ucz-RH9A" points="[22, 0, -91, 216]$[36, 0, -77, 216]$[36, -199, -77, 17]$[112, -199, -1, 17]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OIcFcJx9Eeumk8Ucz-RH9A" id="(0.006329113924050633,0.3291139240506329)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DpJcEJx9Eeumk8Ucz-RH9A" type="4001" element="_DpI1AJx9Eeumk8Ucz-RH9A" source="_DUPjEJx9Eeumk8Ucz-RH9A" target="_usqicJx5Eeumk8Ucz-RH9A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DpJcE5x9Eeumk8Ucz-RH9A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DpJcFJx9Eeumk8Ucz-RH9A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DpJcEZx9Eeumk8Ucz-RH9A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DpJcEpx9Eeumk8Ucz-RH9A" points="[0, 0, -148, -177]$[148, 177, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DpKqMJx9Eeumk8Ucz-RH9A" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DpKqMZx9Eeumk8Ucz-RH9A" id="(0.5,0.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
